### ISSUE TITLE
problem with upload and pins on ESP32

### ISSUE THREAD

**Issue by may1968** [rokrodic/uroflow#2]
Hi Rokrodic,
1) It seems the ESP32 I bought does not have the D6 and D7 pins out - anything I can do? It looks very similar to yours but not exactly - it has nothing but ESP32s printed on back.

2) When I upload the code I get - 
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
partation fail

factory_parameter partition missed

partation fail

1.2.0

[0;31mE (450) phy_init: PHY data partition not found[0m
[0;31mE (450) phy_init: failed to obtain PHY init data[0m
abort() was called at PC 0x400d25c6 on core 0

Backtrace: 0x40090480:0x3ffd7710 0x4009068d:0x3ffd7730 0x400d25c6:0x3ffd7750 0x400dfce5:0x3ffd7780 0x400dfdda:0x3ffd77b0 0x400e00ec:0x3ffd77e0 0x400e0226:0x3ffd7810 0x4009349c:0x3ffd7830 0x4008d82d:0x3ffd7870

Anything I can do?

**Comment by rokrodic** [comment]
Please make sure you have used the non-zero byte file and have moved it into Firmware folder. Run: esptoolESP32.exe --chip esp32 --port COM3 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 esp32/partitions/boot_app0.bin 0x1000 esp32/sdk/bin/bootloader_dio_80m.bin 0x10000 Firmware/UroflowESP32.ino_ESP32.bin 0x8000 Firmware/UroflowESP32.ino.partitions_ESP32.bin
