### ISSUE TITLE
Problems with the Firmware file

### ISSUE THREAD

**Issue by erezkl** [rokrodic/uroflow#3]
Hi Mr. Rodic

I am trying to build a UroFlowMeter using your project. 
I am very new to this, and have a couple of problems:

* When I use your UPLOAD/UPLOADING file that I find in the jithub, the file UroflowESP32.ino_ESP32.bin is empty. It has zero size and I get an error when I run the .bat file (Timed Out waiting for packet header). The other 3 files are written correctly, including the partitions file, but this one is empty, so it looks. 
* I tried to use the file "UroflowESP32.ino.doitESP32devkitV1.bin" instead. this works well, but then the flow meter does not work. The LED stays on all the time and I do not see a wi-fi network when I scan for one  from this machine. 

Please note I am using the ESP32 devkitc_v4 board with ESP-Wroom-32D Ic on it. .

1. Can you point me to the correct file I need to use?
2. Can I get the original .ino files instead of the .bin files so I can try and understand what and how you are doing to get the data?
3. Once everything works, I plan to try and write an android app that will present the data instead of a windows based PC. Did you try doing that as well?

Thank you for your time and help.

**Comment by rokrodic** [comment]
Please follow README.TXT in UPLOADING folder. It explains you have to overwrite the zero-byte file with firmware file and the run apropriate .bat file. Edit .json file beforehand.
